// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mjbQgYuU4Dtd5niP8dyxzB
import * as React from "react";
import { StrapiCredentialsProvider } from "@plasmicpkgs/plasmic-strapi"; // plasmic-import: Nz3wPi974V7/codeComponent

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  strapiCredentialsProviderProps?: Partial<
    Omit<React.ComponentProps<typeof StrapiCredentialsProvider>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, strapiCredentialsProviderProps } = props;

  return (
    <StrapiCredentialsProvider
      {...strapiCredentialsProviderProps}
      host={
        strapiCredentialsProviderProps &&
        "host" in strapiCredentialsProviderProps
          ? strapiCredentialsProviderProps.host!
          : ("https://dev-blog-cdjb.onrender.com/" as const)
      }
      token={
        strapiCredentialsProviderProps &&
        "token" in strapiCredentialsProviderProps
          ? strapiCredentialsProviderProps.token!
          : ("7aac425f1cb8f0879bc057c409a503d56c63d0b100942d360a9b43c344c0700e1ddbfe32691c5a9bce467be0c7c8ccb43f914083c40cccf39b5afcf7adffdb47762024e6fce95acb4ed05ac1189fa9dd5707a83c29132398d36f44459847e85d42c8c92f12a8eb69e5aea3b41e2ffe5a8e8512203561fb3f02863ea1f74784fa" as const)
      }
    >
      {children}
    </StrapiCredentialsProvider>
  );
}
